### PR TITLE
Release notes 1.3

### LINKED ISSUE #533: Change branch structure, point readthedocs to master, introduce stable
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Master will always be pointing to the latest release, dev will contain new developments, documentation on readthedocs will point to master.

### PR DESCRIPTION
**Pull request by michalk8**
**IMPORTANT: Please search among the [Pull request](../pulls) before creating one.**

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] New feature (non-breaking change which adds functionality)

## Closes

closes #533

TODOs:
- [x] write the release notes
- [ ] point latest on RTD to dev, change default to stable (master) - currently stable has problems because of numba (fix on dev)
- [x] add new tutorial to docs
  - [x] creating a new kernel
  - [x] the cytotrace tutorial
- [x] merge #537
- [x] merge #536 
- [ ] ~~merge #534~~ scapped
- [x] merge #547

### CODE REVIEW

**Comment by michalk8** [comment]
@Marius1311 it's 90% done - I've included some TODOs you need to fill (the revamp of panc. adv. + the new tutorial).
I'd also ask you to expand on the CytoTRACE kernel.
I will go over it later today to check links or to look for forgotten features/bugfixes, but I don't think I've missed anything.

**Comment by Marius1311** [comment]
Done, looks good. Just add the recent pyGPCCA PR for stat. dist please, then ready to be merged.

**Comment by michalk8** [comment]
> Done, looks good. Just add the recent pyGPCCA PR for stat. dist please, then ready to be merged.

Thanks, will add it soon. Re merging: this is the last PR to be merged, we still have the about page.

**Comment by michalk8** [comment]
After the tests pass, this can be merged. I will then create a new PR that merged `dev` -> `master`, which will have to wait 'till Monday and after merging https://github.com/theislab/cellrank_notebooks/pull/32.

**Pull request merged**
