### PR TITLE
Fix mapping bug

### LINKED ISSUE #393: Bug in `_map_names_and_colors` when computing many macrostates
I'm calling `g_fwd.compute_metastable_states(cluster_key='clusters', n_states=15, n_cells=30) `

```pytb
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-152-f4f6fa2efa06> in <module>
----> 1 g_fwd.compute_metastable_states(cluster_key='clusters', n_states=15, n_cells=30) # n_states=9
      2 
      3 figure_kwargs = {'dpi': 150, 'discrete': True, 'basis': basis}
      4 if save_figure: figure_kwargs['save'] = 'metastable_states'
      5 g_fwd.plot_metastable_states(legend_loc='right', **figure_kwargs)

~/Projects/cellrank/cellrank/tl/estimators/_gppca.py in compute_metastable_states(self, n_states, n_cells, use_min_chi, cluster_key, en_cutoff, p_thresh)
    174             self._gpcca = self._gpcca.optimize(m=n_states)
    175 
--> 176         self._set_meta_states(
    177             memberships=self._gpcca.memberships,
    178             n_cells=n_cells,

~/Projects/cellrank/cellrank/tl/estimators/_gppca.py in _set_meta_states(self, memberships, n_cells, cluster_key, en_cutoff, p_thresh, check_row_sums)
    886         # _set_categorical_labels creates the names, we still need to remap the group names
    887         orig_cats = metastable_states.cat.categories
--> 888         self._set_categorical_labels(
    889             attr_key=A.META.v,
    890             color_key=A.META_COLORS.v,

~/Projects/cellrank/cellrank/tl/estimators/_base_estimator.py in _set_categorical_labels(self, attr_key, color_key, pretty_attr_key, categories, add_to_existing_error_msg, cluster_key, en_cutoff, p_thresh, add_to_existing)
    766                 )
    767 
--> 768             approx_rcs_names, colors = _map_names_and_colors(
    769                 series_reference=series_reference,
    770                 series_query=series_query,

~/Projects/cellrank/cellrank/tl/_colors.py in _map_names_and_colors(series_reference, series_query, colors_reference, en_cutoff)
    253             color = association_df[association_df["name"] == key]["color"].values[0]
    254             shifted_colors = _create_colors(color, value, saturation_range=None)
--> 255             colors_query_new[np.array(colors_query) == color] = shifted_colors
    256 
    257     association_df["name"] = names_query_new

ValueError: NumPy boolean array indexing assignment cannot assign 2 input values to the 3 output values where the mask is true
```

#### Versions:
cellrank==1.0.0-rc.10 scanpy==1.6.0 anndata==0.7.4 numpy==1.19.1 numba==0.51.0 scipy==1.5.2 pandas==1.1.1 scikit-learn==0.23.2 statsmodels==0.11.1 python-igraph==0.8.2 scvelo==0.2.2 pygam==0.8.0 matplotlib==3.3.1 seaborn==0.10.1
> ...

### PR DESCRIPTION
**Pull request by Marius1311**
**IMPORTANT: Please search among the [Pull request](../pulls) before creating one.**

## Title
Change the way we map colors slightly

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)

## Description
This basically changes the masking for selecting duplicate colors that need to be replaced by new, unique colors. Before, there was a bug when you had non-unique colors in your data

## How has this been tested?
Not at all so far. 

## Closes
closes #393

### CODE REVIEW

**Comment by Marius1311** [comment]
Hi @michalk8 , this fixes the bug. If you don't mind, could you write a quick test for this? Pass annotations with non-unique colors, this should raise a warning but work fine otherwise.

**Comment by michalk8** [comment]
One note for future reference: `np.unique` uses `<` operator, whereas `set` uses hashing. When colors are e.g. strings and tuples, the former doesn't work, the latter does.

**Review by michalk8 — APPROVED** [review]

**Comment by michalk8** [comment]
Also, there's was a very subtle bug (not sure what's happening, but it's fixed by using the Series instead of an array):
```python
x = pd.Series(["a", "b", np.nan, "b", np.nan, 'a', 'a']).astype("category")
y = pd.Series(["b", np.nan, np.nan, "d", "a", 'c', 'x']).astype("category")

_, colors = _map_names_and_colors(x, y, colors_reference=["blue", "red"])
```
I expect 4 different hues of blue, but:
```python
# before
['#000066', '#000033', '#113300', '#ff0000', '#669900']  # the last is khaki-like, should be blue-like
# after
['#006bb2', '#0034c8', '#1300de', '#ff0000', '#6900f4']  # all except the red are blue-like, as expected
```

**Comment by Marius1311** [comment]
Excellent, great work!

**Comment by Marius1311** [comment]
Feel free to merge this whenever you're ready.

**Pull request merged**
