### PR TITLE
Process series

### PR DESCRIPTION
**Pull request by Marius1311**
This cleans up some of the markov chain utility function.

### CODE REVIEW

**Comment by Marius1311** [comment]
@michalk8 , why are checks not running automatically on this?

**Comment by michalk8** [comment]
It is, but fore some reason, download of `adata` objects failed (server error). I will restart the tests.
Also would be great if you could add tests for the new functions.

**Comment by Marius1311** [comment]
yes, will do. They are actually the same as the old functions, just written a bit more general.

**Comment by Marius1311** [comment]
any progress on this yet?

**Comment by michalk8** [comment]
All I can do is to restart the job again. I don't know why it's failing (now it was 504 - gateway timeout).
I will look on the web to see if there's some issue with travis.

**Comment by michalk8** [comment]
@Marius1311 no idea why the issues arose, but restarting the jobs now worked.

**Comment by Marius1311** [comment]
Thanks!

**Comment by Marius1311** [comment]
Hi Mike, would you mind writing the tests? I'm really trying to push for the figure atm. The functions are just generalizations of the functions we have already and I think their purpose is well documented in the docstrings. Let me know whether that works for you.

**Comment by michalk8** [comment]
Sure, I can write the tests.

**Comment by Marius1311** [comment]
Thanks!

**Pull request merged**
