### PR TITLE
Support raw

### LINKED ISSUE #286: `cr.pl.heatmap` for genes from adata.raw
- [x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

So far, our heatmap plotting function can't be used for genes which are only in `adata.raw.var_names`. Adding support for .raw would be nice.

### PR DESCRIPTION
**Pull request by michalk8**
**IMPORTANT: Please search among the [Pull request](../pulls) before creating one.**

## Title

Support .raw for plotting functions which use Model.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] New feature (non-breaking change which adds functionality)

## Description
Added `use_raw=...` to Model.prepare.

## How has this been tested?

3 new tests have been added.

## Closes

closes #286

### CODE REVIEW

**Comment by Marius1311** [comment]
Fantastic, thanks!

**Comment by Marius1311** [comment]
Hi Mike, this doesn't quite work for me yet. I just pulled from master. First of all, the `use_raw` parameter isn't exposed in the `cr.pl.heatmap` function. Second, when I set it anyways, I get
```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-58-47301dd0e1a4> in <module>
      3 cr.pl.heatmap(adata[basal_likely_mask].copy(), model, genes=basal_genes, lineages=['Basal'], 
      4               cluster_key='clusters_coarse', use_raw=True,
----> 5               show_absorption_probabilities=True, figsize=(10, 15), show_all_genes=True) 

~/Projects/cellrank/cellrank/plotting/_heatmap.py in heatmap(adata, model, genes, backward, kind, lineages, start_lineage, end_lineage, cluster_key, show_absorption_probabilities, cluster_genes, scale, n_convolve, show_all_genes, show_cbar, lineage_height, xlabel, cmap, n_jobs, backend, show_progress_bar, figsize, dpi, save, **kwargs)
    457         genes = [genes]
    458     genes = _unique_order_preserving(genes)
--> 459     check_collection(adata, genes, "var_names")
    460 
    461     if isinstance(start_lineage, (str, type(None))):

~/Projects/cellrank/cellrank/utils/_utils.py in check_collection(adata, needles, attr_name, key_name)
     38     for needle in needles:
     39         if needle not in haystack:
---> 40             raise KeyError(f"{key_name} `{needle}` not found in `adata.{attr_name}`.")
     41 
     42 

KeyError: 'Gene `Aqp3` not found in `adata.var_names`.'
```
The error message is confusing because it implies that the gene was searched for in `adata.var_names`, rather than `adata.raw.var_names`, and also 
```
'Aqp3' in adata.raw.var_names
``` 
is `True`.

**Comment by Marius1311** [comment]
However, `'Aqp3' in adata.var_names` is `False`, as expected.

**Comment by michalk8** [comment]
Completely forgout about this one and the tests didn't catch it (will have to modify how I set the .raw attribute in them).
Should be fixed in https://github.com/theislab/cellrank/commit/c86008977dcecda729645042007274ade2df69b7
Note that `GamMGCVModel` pickling is bugged (used when `n_jobs!=1)`, will be dealt with in https://github.com/theislab/cellrank/pull/289

**Comment by Marius1311** [comment]
great, thanks! Is there a way to globally set the number of cores used in model fits?

**Comment by Marius1311** [comment]
if so, I think we should expose this in our docs.

**Comment by michalk8** [comment]
Not yet, we're still using scanpy's settings and need to move to our own settings to make this work.

**Comment by Marius1311** [comment]
okay, got it. Increasing the `n_jobs` parameter in the heatmap function worked very nice for me, there was a significant speedup!

**Pull request merged**
