### PR TITLE
Fix lineage repr

### LINKED ISSUE #249: Add pie chart plotting for the lineage class
Would be super nice if a lineage object would have a convenient way to visualise distributions, ie in pie charts. I'm thinking of a method `lineage.plot_pie_chart(mask: Optional[Iterable[bool]] = None)`, where mask is optional and could select a cluster. The method should compute the mean over all cells selected by the mask along axis 0 and plot something like the below:
image

where names and colors can be taken from the lineage object directly!

### PR DESCRIPTION
**Pull request by michalk8**
There's still a significan bug - the probabilites are not normalized to 1.

closes #249 #248

### CODE REVIEW

**Comment by michalk8** [comment]
@Marius1311 I've changed the functionality of `Lineage` - I've modified function which operate on `Lineage` so that most of them should be shape-preserving, so beware.
Most importantly, the `html_repr` should be more robust - it works on transposed data as well (overall better handling there), + the reduction along 0th, 1st axis also display the function name.
I've also included the plotting fn, slightly modified (don't think we need the parameter you've suggested, we can always subset the object).
There's an issue with `.X` attribute - `similarity_plots` test fail if we don't copy the data (which we don't want to) - it's due to the fact that the rows don't sum to 1. I can't find the problem, if you have the time, I'd appreciate if you could look into it.

**Comment by Marius1311** [comment]
Hi MIke, sorry, I don't really understand what the problem is here, I think it's best if you explain this to me tomorrow, then I will have a look at it.

**Comment by michalk8** [comment]
@Marius1311 it's simple, somewhere, we have an `inplace` operation which modifies the values of lineage probabilities.
If using `.X` return a copy, everything's fine
I have a suspect: I've changed the reductions to not use `.copy` (seemed unnecesary - I've checked the code [but probably not thoroughly enough] and found no reason to do so): https://github.com/theislab/cellrank/pull/250/files#diff-afc45402aad45051cca8a4f21845bcf6L543
Since you've written it, maybe you know better.

**Comment by michalk8** [comment]
I think I will create a separate issue for this afterwards.

**Comment by michalk8** [comment]
Ok, going to merge this, tests pass. Will create a new issue regarding `.X`.

**Pull request merged**
