### PR TITLE
Negative binomial

### LINKED ISSUE #377: Negative binomial
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [x] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

TODOs:
- [ ] implement weighted models in batchglm (numpy backend only)
- [ ] interface batchglm using our models
- [ ] either update or remove (in favor of batchglm) GAMR
- [ ] implement tradeSeq-like model fitting (categorical term for lineage assignment, diff pseudotimes, knot placement, etc.)

### LINKED ISSUE #424: Remove deprecated function
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [x] Other?

### PR DESCRIPTION
**Pull request by michalk8**
**IMPORTANT: Please search among the [Pull request](../pulls) before creating one.**

## Title

Add negative binomial support, similarly to tradeSeq.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] New feature (non-breaking change which adds functionality)

## Description

Add NB support for `cellrank.ul.models.GAMR`, use its confidence interval (95% by default), remove `gam`
backend. Add automatic knot locations.

## How has this been tested?

Not yet.

## Closes

closes #377 
closes #424

## TODOs
- [x] improve _get_offset (numba or at very least vectorize, not parallelize)
- [x] clean up the code (i.e. missing)
- [x] better passing of offset? i.e. not per-init basis, but compute only 1 and pass it from top-level fns (current TMM impl
is slow, maybe numba/vectorization will help - in that case, leave it as it is)
- [x] expose spline type (default we're using cubic)
- [x] expose fixed effects (maybe later as an enhancement [we could support patsy formulas])
- [x] write tests
- [x] enable rpy2 on Travis

### CODE REVIEW

**Comment by michalk8** [comment]
@Marius1311 I think I'm done here. I was thinking of exposing more parameters from https://www.rdocumentation.org/packages/mgcv/versions/1.8-33/topics/gam, but for now, I think it's not necessary.
I've tested the offset calculation to its R counterpart, getting very similary results (differences arise from R's `rank` and `scipy.stats.rankdata`.
The initial model loading might be a bit slow (might need to tweak or maybe expose the params - currently, it's 4 threads + a numba function),
but it needs to be calculated only once (it's cached under `adata.obs['cellrank_offset']`).
As for speed, for the NB, it's ~5 genes x 3 lineages per second on 8 cores, much slower than the gaussian GAM.

Tomorrow, I will write start and hopefully finish writing tests (still need to look into model copying) and I think I can merge it (plots look much better).

**Comment by Marius1311** [comment]
Hi Mike, before we merge this, we need to discuss over zoom. We can't introduce backwards compat. breaking changes right now.

**Comment by Marius1311** [comment]
Also, what exactly changed about the confidence interval computation? Are the changes only in respect to NB, or also to the Gaussian noise model?

**Comment by michalk8** [comment]
Need to figure out why SLEPc fails on Bionic and not on Xenial.

**Comment by Marius1311** [comment]
What's the state of the art here?

**Comment by michalk8** [comment]
Need to figure out why on newer Ubuntu version SLEPc fails (or possibly go back to Xenial).
Then I need to write tests. I hope to merge this by the end of the day along with #419 and make a new release.

**Comment by Marius1311** [comment]
Excellent, thanks.

**Comment by michalk8** [comment]
TODOs:
- [ ] allow returning of models
- [ ] write docstrings + typing
- [ ] write tests
- [ ] optional: add cloudpickle to support pickling of enums for Python3.6 (i.e. estimator + models)

**Comment by Marius1311** [comment]
Well done, thanks Mike.

**Pull request merged**
