### PR TITLE
Expose keyworded arguments for the trans_mat funciton

### PR DESCRIPTION
**Pull request by Marius1311**
**IMPORTANT: Please search among the [Pull request](../pulls) before creating one.**

## Title
Give more control in the high level transition matrix function

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] New feature (non-breaking change which adds functionality)

## Description
This exposes some arguments from the underlying kernels in the high level transition matrix funciton

## How has this been tested?
Not at all.

### CODE REVIEW

**Comment by Marius1311** [comment]
@michalk8 we could make this more general and expose kwargs from both the velo kernel and the connectivity kernel, what's your opinion?

**Review by michalk8 — APPROVED** [review]
I'd go for the following, as you already did, in VK: mode, backward_mode and softmax_scale
For CK: I think it's just density_norm, so no need to pack it under kwargs (if we introduce more arguments in the future, than sure).

**Comment by michalk8** [comment]
I think this is fine. Merging.

**Comment by Marius1311** [comment]
Great, thanks for looking into it

**Pull request merged**
