### PR TITLE
Enable towncrier

### LINKED ISSUE #688: Latest release notes in docs
## Description

ATM, the latest release notes are not listed in the section *Release Notes* on the ReadTheDocs page but only on the landing page. This is a bit counter intuitive. The detailed change log which is currently only on the landing page should be visible in the *Release Notes* section as well.

### LINKED ISSUE #689: Update feature request issue template
## Description

The tick boxes in the current issue template are shown as not yet completed tasks in GitHub. This can be confusing as it suggests there is some unfinished work. We can remove the list and add labels instead. This has the additional advantage of easily finding issues by setting a filter on the labels.

### PR DESCRIPTION
**Pull request by michalk8**
**IMPORTANT: Please search among the [Pull requests](../pulls) before creating one.**

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] New feature (non-breaking change which adds functionality)

## Description

Enable towncrier for release notes generation.

## How has this been tested?

N/A

## Have release notes been modified?

TODO: remove this section

## Closes

closes #688
closes #689

### CODE REVIEW

**Comment by Marius1311** [comment]
I'm okay with opt-in. Can you post a screenshot of the format please?

**Comment by michalk8** [comment]
> I'm okay with opt-out. Can you post a screenshot of the format please?

@Marius1311 @WeilerP which ones you prefer?
1. doesn't read the issue title, just renders the description as list (closely matches to what we have now)
first
2. adds the title as heading and renders the description below
second

I don't really have any preference, currently it's `1.` (just need to change 2 lines to switch to `2.`). Once we've converge on the format, this can be merged.

**Comment by Marius1311** [comment]
I vote for the first option. @WeilerP ?

**Comment by WeilerP** [comment]
I also prefer the first option.

**Comment by michalk8** [comment]
@ManuSetty @WeilerP thanks, then I think it's settled. Hope the CI works again (if not, will fix it in a subsequent PR).

**Pull request merged**
