### PR TITLE
Random walk simulation

### LINKED ISSUE #529: Add simulations for kernels
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [x] Other?

...

### PR DESCRIPTION
**Pull request by michalk8**
**IMPORTANT: Please search among the [Pull request](../pulls) before creating one.**

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] New feature (non-breaking change which adds functionality)

## Description

Add random walks on MC + corresponding plotting in KernelExpression class.

## How has this been tested?

Not yet.

## Closes

closes #529 

TODOs:
- [x] tests for RW class
- [x] plotting tests

### CODE REVIEW

**Comment by michalk8** [comment]
@Marius1311 I will start adding tests, in the meantime, you could give it a try.

**Comment by Marius1311** [comment]
Amazing, will check this out today!

**Comment by michalk8** [comment]
> Amazing, will check this out today!

Thanks Marius, let me know if you have any further requests. If not, this can be merged once the tests pass.

**Comment by Marius1311** [comment]
Comments 
- Can we call the method `plot_random_walks` (with an "s") please?
- Can we add a legend for the way in which we show the first and the last cell in a random walk? If that's an overkill or if it complicated things with the default scVelo legend, please just mention it in the `Returns` statement of the method
- `max_iter` description, should it be "[...] it can be specified as a fraction of the number **cells**"?

Sorry need to stop here, will get back to this later.

**Comment by michalk8** [comment]
Thanks for the comments in https://github.com/theislab/cellrank/pull/537#issuecomment-804106526 @Marius1311 , all done.

**Comment by Marius1311** [comment]
A number of colorbars (i.e. `viridis`, `inferno`, `plasma`) give the following error (I call `ptk.plot_random_walks(n_sims=10, cmap='inferno')`:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-25-80671cc25ddb> in <module>
----> 1 ptk.plot_random_walks(n_sims=10, cmap='inferno')

~/Projects/cellrank/cellrank/tl/kernels/_base_kernel.py in plot_random_walks(self, n_sims, max_iter, seed, successive_hits, start_ixs, stop_ixs, basis, cmap, linewidth, linealpha, ixs_legend_loc, n_jobs, backend, show_progress_bar, figsize, dpi, save, **kwargs)
    464                 segments,
    465                 linewidths=linewidth,
--> 466                 colors=[cmap(float(i) / n_seg) for i in range(n_seg)],
    467                 alpha=linealpha,
    468                 zorder=2,

~/Projects/cellrank/cellrank/tl/kernels/_base_kernel.py in <listcomp>(.0)
    464                 segments,
    465                 linewidths=linewidth,
--> 466                 colors=[cmap(float(i) / n_seg) for i in range(n_seg)],
    467                 alpha=linealpha,
    468                 zorder=2,

~/miniconda3/envs/py38_devel/lib/python3.8/site-packages/matplotlib/colors.py in __call__(self, X, alpha, bytes)
    566         """
    567         if not self._isinit:
--> 568             self._init()
    569 
    570         mask_bad = X.mask if np.ma.is_masked(X) else np.isnan(X)  # Mask nan's.

~/miniconda3/envs/py38_devel/lib/python3.8/site-packages/matplotlib/colors.py in _init(self)
    757     def _init(self):
    758         self._lut = np.ones((self.N + 3, 4), float)
--> 759         self._lut[:-3, 0] = _create_lookup_table(
    760             self.N, self._segmentdata['red'], self._gamma)
    761         self._lut[:-3, 1] = _create_lookup_table(

ValueError: could not broadcast input array from shape (2) into shape (0)
```

Note: this does not happen for gnuplot or gnuplot2.

**Comment by Marius1311** [comment]
Apart from that, I did some minor additions to the docstring - once the above error is fixed and the tests pass, this can be merged.

**Comment by Marius1311** [comment]
Very nice work @michalk8, really insightful.

**Comment by Marius1311** [comment]
Plots like this one below are nice - they show you were you move if you're initialized "in the middle"
image

**Comment by michalk8** [comment]
> A number of colorbars (i.e. viridis, inferno, plasma) give the following error (I call ptk.plot_random_walks(n_sims=10, cmap='inferno'):

Can't reproduce (on the CI, I have a test with `viridis`), what's your matplotlib version? Mine is `3.3.4`.

**Comment by Marius1311** [comment]
> > A number of colorbars (i.e. viridis, inferno, plasma) give the following error (I call ptk.plot_random_walks(n_sims=10, cmap='inferno'):
> 
> @Marius1311 Can't reproduce locally (on the CI, I have a test with `viridis`), what's your matplotlib version? Mine is `3.3.4`.

Mine is 3.3.2, I will try upgrading to 3.3.4

**Comment by Marius1311** [comment]
Can't reproduce the error, happy for you to merge this.

**Pull request merged**
