### PR TITLE
Gpcca overlap

### PR DESCRIPTION
**Pull request by michalk8**
Implements #116

### CODE REVIEW

**Comment by michalk8** [comment]
@Marius1311 could you please check this whether it's running as expected, e.g. on the Lung data?
I've tested it and should be working as expected, but I could you another pair of eyes to test it.
If it works, I will merge this and focus on tests, since they are deeply needed.

**Comment by Marius1311** [comment]
Thanks a lot Mike, this is on my agenda for today!

**Comment by michalk8** [comment]
@Marius1311 anything from your side? If not, I'd merge it.

**Comment by Marius1311** [comment]
Comments
- color mapping is off, see Fig 1 below. This is really important, we had lots of issues with this before so please make sure this does not break and include some tests for color/name mapping. 

## Fig 1
image
image

**Comment by Marius1311** [comment]
Also, on a more fundamental level, this does not give us what we want for many states. The approach has to be changed fundamentally, using the metastable assignment is not the right approach.

**Comment by Marius1311** [comment]
I was just about to post a plot for this.

**Comment by Marius1311** [comment]
image
Using the old approach to select cells/give names to states

image
New approach (using the `metastable assignment`). Pretty much **everything** is in the completely wrong place.

**Comment by michalk8** [comment]
Seems like an issue with naming/colors. Should I start fixing this? Basedon what you've said below, I'm not sure.

> Also, on a more fundamental level, this does not give us what we want for many states. The approach has to be changed fundamentally, using the metastable assignment is not the right approach.

**Comment by Marius1311** [comment]
mhm, it's a bit hard to tell at the moment whether it's something fundamental or naming colors. Maybe fix naming/colors, update the branch, and I will test again.

**Comment by Marius1311** [comment]
Maybe I was too quick in calling this a fundamental problem.

**Comment by michalk8** [comment]
@Marius1311 could you please check if the fix works? For me, it does.

**Comment by Marius1311** [comment]
Thanks, will give it a go

**Comment by Marius1311** [comment]
This is weird: it works perfectly for 9 states (Fig 1), but then gets everything wrong (colors & names) for 11 states (Fig 2) (10 does not work, splits pair of complex conjugates) 

## Fig 1
image


## Fig 2
image

Once this is solved, let's please add some checks for name/color mapping

**Comment by michalk8** [comment]
Can you upload the adata object + notebook for me please? I have no idea why this happens...

**Comment by michalk8** [comment]
I've fixed a few nasty bugs, but I don't think any of them caused the issue above (maybe I'm wrong).
Still, I'd appreciate the `adata` object + notebooks to reproduce it. I've tried on the pancreas basic various values (3-20), the mapping seems fine.

**Comment by Marius1311** [comment]
Hi @michalk8 , sorry, I didn't see your latest comments yesterday, I will try this again and if the error persists, send you the AnnData object and notebook to reproduce!

**Comment by michalk8** [comment]
@Marius1311 any news? It's really bugging me since I can't trace the bug.

**Comment by Marius1311** [comment]
sorry, was caught up in something else. Getting to it now.

**Comment by Marius1311** [comment]
Really sorry, I must correct myself, this is working as expected. I don't know whether your recent commits fixed it, or whether I made a mistake. 

Now, the only thing I'm worried about is the massive (repeated) output, e.g. for 16 states: 
```
Computing metastable states
INFO: Using pre-computed schur decomposition
WARNING: Number of requested cells (30) exceeds the number of available cells (26) for cluster `13`. Selecting all cells
WARNING: Number of requested cells (30) exceeds the number of available cells (26) for cluster `2`. Selecting all cells
WARNING: Number of requested cells (30) exceeds the number of available cells (28) for cluster `6`. Selecting all cells
WARNING: Number of requested cells (30) exceeds the number of available cells (9) for cluster `3`. Selecting all cells
WARNING: Number of requested cells (30) exceeds the number of available cells (11) for cluster `0`. Selecting all cells
Adding `.schur_vectors`
       `.metastable_states`
       `.coarse_T`
       `.coarse_stationary_distribution`
    Finish (0:00:20)
WARNING: Number of requested cells (30) exceeds the number of available cells (26) for cluster `Alpha_2`. Selecting all cells
WARNING: Number of requested cells (30) exceeds the number of available cells (26) for cluster `Delta`. Selecting all cells
WARNING: Number of requested cells (30) exceeds the number of available cells (28) for cluster `Epsilon_1`. Selecting all cells
WARNING: Number of requested cells (30) exceeds the number of available cells (9) for cluster `Ngn3 low EP_3`. Selecting all cells
WARNING: Number of requested cells (30) exceeds the number of available cells (11) for cluster `Ngn3 low EP_1`. Selecting all cells
```

Can we summarise this somehow, and make sure we don't get it twice? I.e. once with just numbers as labels, once with mapped cluster annoations?

**Comment by Marius1311** [comment]
Once this is fixed, please go ahead and merge.

**Comment by michalk8** [comment]
Should be fixed by now, will merge once the tests pass. After this, I will focus on the tests.

**Pull request merged**
