### PR TITLE
Add more TODOs

### LINKED ISSUE #448: Morris reprogramming data
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [x] Other?

New dataset: `cellrank.datasets.reprogramming` from https://github.com/morris-lab/BiddyetalWorkflow
TODOs:
- [x] clean the object
- [ ] post it on the figshare
- [ ] create the function with arguments to subset the 45k/85k
- [ ] nicely explain what are the obs (@Marius1311 )

I wouldn't test for download of this since it will be quite large (compare to the other we have).
Once this is and #445 is done, it's time for 1.1.0 release (hopefully Monday the latest).

### PR DESCRIPTION
**Pull request by michalk8**
**IMPORTANT: Please search among the [Pull request](../pulls) before creating one.**

## Title

Add `cellrank.datasets.reprogramming`.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] New feature (non-breaking change which adds functionality)

## Description

Add reprogramming dataset from add_new_terminal_states_method 

## How has this been tested?

Not and it will not be (on CI), since the data  has ~1.5 GiB.

## Closes

closes #448

### CODE REVIEW

**Comment by michalk8** [comment]
@Marius1311 
here are the things you need to fill in:
- https://github.com/theislab/cellrank/blob/add_morris_data/cellrank/datasets/_datasets.py#L171
- https://github.com/theislab/cellrank/blob/master/docs/source/latest_additions.rst

The dataset will have the following columns:
```python3
timecourse           category
reprogramming_day    category
reprogramming         category   # whether it's dead end or it's reprogramming
cell_type             category
cell_cycle           category
clusters             category
monocle_state        category
pseudotime            float64
CellTagD0_85k             float64
CellTagD3_85k             float64
CellTagD13_85k            float64
CellTagD0_48k         float64
CellTagD3_48k         float64
CellTagD13_48k        float64
dtype: object
```

**Comment by Marius1311** [comment]
Hi Mike, I'm done with the docs, the updated dataset is currently uploading and should be done in a few minutes!

**Comment by michalk8** [comment]
@Marius1311 thanks, once it's uploaded, I will finish the function.

**Comment by Marius1311** [comment]
Hi Mike, the upload is done, the link should stay the same but you can easily check this from the public collection: https://figshare.com/collections/CellRank_for_directed_single-cell_fate_mapping_-_datasets/5172299

**Comment by Marius1311** [comment]
thanks!

**Comment by michalk8** [comment]
Thanks @Marius1311.

**Pull request merged**
