### PR TITLE
Add circular projection

### LINKED ISSUE #457: Visualizing lineage probabilities on a circle/simplex
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [x] New plotting function in `cr.pl`?
- [x] Other?

Hi, thanks a lot for this awesome toolkit! I was wondering whether you've looked into adding functionality to visualize absorption probabilities for more than 2 lineages on a circle/simplex, similarly to [STEMNET](https://www.nature.com/articles/ncb3493/figures/5). 

I've found this very useful on my own dataset, adding the projection of probabilities to cartesian coordinates to `obsm` and plotting with `sc.pl.embedding`.
```
import scanpy as sc
import numpy as np
import cellrank as cr
import matplotlib.pyplot as plt
import math

def prob2simplex(adata):
    p_mat = adata.obsm['to_terminal_states'].X
    
    ## Assign each terminal state to an angle on the edge of a circle
    n_lin = p_mat.shape[1]
    angle_vec = [x*(360/n_lin) for x in range(n_lin)]
    angle_vec = [math.radians(x) for x in angle_vec]
    
    ## Transform to cartesian coordinates
    x2 = (p_mat * np.cos(angle_vec)).sum(1)
    y2 = (p_mat * np.sin(angle_vec)).sum(1)
    
    ## Add to embeddings
    adata.obsm["X_fate_simplex"] =  np.array([y2, x2]).T

adata = cr.datasets.pancreas_preprocessed() 

## Calculate lineage probabilities
cr.tl.terminal_states(adata, cluster_key='clusters', weight_connectivities=0.2)
cr.tl.lineages(adata)

## Add simplex embedding
prob2simplex(adata)

plt.rcParams["figure.figsize"] = [8,8]
sc.pl.embedding(adata, "X_fate_simplex", color="terminal_states",  frameon=False, size=40, legend_loc="on data")
sc.pl.embedding(adata, "X_fate_simplex", color="clusters_fine",  frameon=False, size=40, legend_loc="on data")
```
Output:
Screenshot 2020-12-18 at 08 42 43
Screenshot 2020-12-18 at 08 42 50

### PR DESCRIPTION
**Pull request by michalk8**
**IMPORTANT: Please search among the [Pull request](../pulls) before creating one.**

## Title

Add new way of plotting lineage probabilities - `cellrank.pl.circular_projection`.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] New feature (non-breaking change which adds functionality)

## Description

Add circular embedding as described in STEMNET (here's an [example](https://www.nature.com/articles/ncb3493/figures/5)).

## How has this been tested?

It hasn't yet.

## Closes

closes #457 

TODOs:
- [ ] better defaults/placement of labels?
- [ ] tests
- [ ] determine if we want to add the 2 metrics (priming_degree and priming_direction)*
- [ ] look at approximate TSP? currently, it takes ~4 mins for 20 lineages (pancreas) to find the optimal ordering.
I'm using Karp-Held, which has complexity of O(n\*\*2 2\*\*2) (vs. the brute-force using perms of O(n!), where n is the number of lineages, though faster, approx. solution might be better**
- [ ] add a small example

* @Marius1311 the degree looks like a KL-divergence with the average lineage probability, the direction is a hard-assignment (just an argmanx on the scaled lineage probs by their means).
So far, I've only included the first. Would be great if we could test this first if it makes sense for us to include it here.

** The ordering def. cleans up the visualization, at least for the case below:
```python3
import cellrank as cr

adata = cr.datasets.pancreas_preprocessed() 

cr.tl.terminal_states(adata, cluster_key='clusters', weight_connectivities=0.2, n_states=11)
cr.tl.lineages(adata)

# by default, I've chosen the correlation metric to construct the distance matrix - this differs from what is done in STEMNET
(they maximize the path and the distance matrix is constructed a dot product beween lineages)
# plot using the default ordering
cr.pl.circular_projection(adata, ["clusters", "dpt_pseudotime"], lineage_order="default",
                          space=0.75)

# solve the optim. problem, should be still fairly fast (<2s)
cr.pl.circular_projection(adata, ["clusters", "dpt_pseudotime"], lineage_order="optimal",
                          space=0.75)
```

and the output in order:
(PNG-Grafik, 608 × 334 Pixel)
(PNG-Grafik, 582 × 334 Pixel)

### CODE REVIEW

**Comment by Marius1311** [comment]
Hi @michalk8, here are my point-by-point comments
- Re the two metrics you mentioned: yes, let's do that, should be easy and might give us a nice pseudo-temporal ordering, let's check this out. 
- Re TSP - what do you mean by "TSP"? 
- Re your plots - I assume you're demonstrating the effect of the optimal arrangement of developmental endpoints - from the STEMNET paper: "To find the optimal arrangement of the developmental endpoints on the circle, lineages with common precursor stages are placed next to each other. [...] ". 
- What I don't understand in your plots: why don't I see the "star shape" I am familiar with from the STEMNET plots, or also from https://github.com/theislab/cellrank/issues/457? Are you sure to be visualising absorption probabilities towards terminal populations?
- Please make sure to give the STEMNET paper to appropriate credit in docstrings etc.

**Comment by michalk8** [comment]
> Re the two metrics you mentioned: yes, let's do that, should be easy and might give us a nice pseudo-temporal ordering, let's check this out.

Done.

> Re TSP - what do you mean by "TSP"?
TSP is Travelling salesman problem - the shortest path visiting all nodes exactly once, starting and ending in the same node. That's the opt. technique for ordering the lineages. 

> Re your plots - I assume you're demonstrating the effect of the optimal arrangement of developmental endpoints - from the STEMNET paper: "To find the optimal arrangement of the developmental endpoints on the circle, lineages with common precursor stages are placed next to each other. [...] ".

Yes.

> What I don't understand in your plots: why don't I see the "star shape" I am familiar with from the STEMNET plots, or also from #457? Are you sure to be visualising absorption probabilities towards terminal populations?

No, I was just trying to test the performance of TSP on 11 nodes (for 20 nodes, it takes ~3-4min on my PC to solve it).

> Please make sure to give the STEMNET paper to appropriate credit in docstrings etc.

Done in the docstring under `[Velten17]`.

**Comment by michalk8** [comment]
I've cleaned up the visualization by including pie-chart wedges (can be disabled). Also added nicer label placement (default is `'best'` - useful for readability, seen below).
```python
cr.pl.circular_projection(adata, ["priming_direction", "priming_degree", "clusters", "dpt_pseudotime"],
                          hide_wedges=False, legend_loc='upper right',
                          ncols=2, space=0.3)
```
new

**Comment by michalk8** [comment]
> I understand in your plots: why don't I see the "star shape" I am familiar with from the STEMNET plots, or also from #457? Are you sure to be visualising absorption probabilities towards terminal populations?

The star shape was error on my side, I was missing the normalization by mean abs. prob as done in STEMNET.
Here's the updated version.

new

**Comment by Marius1311** [comment]
That looks really nice @michalk8 !

**Comment by Marius1311** [comment]
Let me know once everything is done so I can go over the maths to check whether everything is in fact correct.

**Comment by Marius1311** [comment]
And re TSP: there is a wealth of approximate solution algorithms available, however, I don't think that's necessary at this point - this is really of marginal importance. We can always to back to this question in case we ever encounter a large dataset with 20 endpoints that we need a circular projection for.

**Comment by michalk8** [comment]
The tests seem to be failing because: https://gitlab.com/petsc/petsc/-/issues/803

**Pull request merged**
