### PR TITLE
Move GDPT

### PR DESCRIPTION
**Pull request by michalk8**
Implements #158

### CODE REVIEW

**Comment by Marius1311** [comment]
Nice! I just had a quick look and it seems like this already makes use of the pre-computed schur decomposition? This would be very nice.

**Comment by michalk8** [comment]
Yes, it's already using precomputed Schur vectors. Can I merge it?

**Comment by Marius1311** [comment]
Sure, go ahead.

**Comment by Marius1311** [comment]
Do we generally make sure we fall back to `brandts` when to SLEPSc is installed, whenever `.compute_schur` is called? This would be important.

**Comment by michalk8** [comment]
That behavior is implemented within `msmtools`.

**Pull request merged**
