### PR TITLE
Remove default value for `time_key` argument

### LINKED ISSUE #988: Change default time key for `time_key`
At the moment, the default time key for plotting gene trends (and other high-level functions) is `time_key="latent_time"`. I think it'd be a good idea to remove the default value since it appears to be an artifact from when CellRank was designed as a downstream analysis tool for RNA velocity.

### PR DESCRIPTION
**Pull request by WeilerP**
## Description

* Removes default value for `time_key`.

## Closes

Closes #988.

### CODE REVIEW

**Comment by WeilerP** [comment]
@michalk8, should we also remove the default value in `cellrank.pl.log_odds`? ATM, it is set to `"exp_time"`. There is no reason why the experimental time information should/would be identified this way, though, IMO.

**Comment by WeilerP** [comment]
Also, any immediate idea why the CI is failing, @michalk8? At first glance, it seems unrelated to the introduced changes, I would say.

**Comment by michalk8** [comment]
> Also, any immediate idea why the CI is failing, @michalk8? At first glance, it seems unrelated to the introduced changes, I would say.

Defaults in tests are missing:

- `gene_trends() missing 1 required positional argument: 'time_key'`
- `_plot_dispatcher() missing 1 required positional argument: 'time_key'`
- ...

**Comment by WeilerP** [comment]
> Defaults in tests are missing:

Ah, sorry, my bad. I didn't realize GitHub displayed a collapsed version of the logs, and I only saw some install logs. Thanks!

**Review by michalk8 — APPROVED** [review]
LGTM, thanks @WeilerP !

**Comment by Marius1311** [comment]
LGTM, again what learned.

**Comment by WeilerP** [comment]
> LGTM, thanks @WeilerP !

Still gotta remove the default value in `BaseModel.prepare`, and `_plot_continuous` and `_plot_dispatcher` in `cellrank.estimatory.mixins._utils.py`.

**Comment by WeilerP** [comment]
@michalk8, do you have a good suggestion for how to modify [`_create_callbacks`](https://github.com/theislab/cellrank/blob/6150f029dcfd320d9a49af114fe805633b920671/cellrank/pl/_utils.py#L767) to work with the new API of `BaseModel.prepare`?

**Comment by michalk8** [comment]
@WeilerP I think `test_callback_lineage_and_gene_specific` is missing `time_key`. After this is fixed, please feel free to merge!

**Review by michalk8 — APPROVED** [review]

**Pull request merged**
