### PR TITLE
Enable showing no legend

### PR DESCRIPTION
**Pull request by Marius1311**
**IMPORTANT: Please search among the [Pull request](../pulls) before creating one.**

## Title
Really simple fix when I want to show no legend when plotting

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] New feature (non-breaking change which adds functionality)

## Description
This enables showing no legend in the `_plot_real_spectrum` method when passing `legend="none"`

## How has this been tested?
Not at all.

### CODE REVIEW

**Comment by Marius1311** [comment]
@michalk8 any idea why the docs are failing here?

**Comment by Marius1311** [comment]
About this PR: I should probably be more consistent about this change and enable everywhere that passing `legend_loc="none"` means that no legend is shown - that's the way it's handled in scvelo, and since many of our plotting functions are based on scvelo, we internally use this already.

**Comment by michalk8** [comment]
> @michalk8 any idea why the docs are failing here?

Time-out, it sometimes happen. As long as the tests pass, it should be fine.

**Comment by Marius1311** [comment]
Ok, thanks!

**Comment by michalk8** [comment]
@Marius1311 this should cover it (or at least most of the cases). Feel free to review/merge.

**Comment by Marius1311** [comment]
Looks good. I'm just re-running the tests to see if they pass, feel free to merge once they do.

**Comment by michalk8** [comment]
Locally, everything passes, merging.

**Comment by Marius1311** [comment]
nice!

**Pull request merged**
