### PR TITLE
Expose kwargs in spectral plotting

### PR DESCRIPTION
**Pull request by Marius1311**
**IMPORTANT: Please search among the [Pull request](../pulls) before creating one.**

## Title
Expose kwargs in spectral plotting

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)

## Description
Just exposes some argumetns when plotting eigenvalues. 

## How has this been tested?
No tests have been added or modified.

### CODE REVIEW

**Comment by Marius1311** [comment]
Why was there only a single check executed, which is building the docs?

**Comment by Marius1311** [comment]
Oh, suddently the other tests started as well. Never mind then.

**Review by michalk8 — APPROVED** [review]
I've just added tests.

**Comment by Marius1311** [comment]
thanks mike!

**Pull request merged**
