### PR TITLE
Feature/prune lineage class

### LINKED ISSUE #777: Refactor Lineage class
TODOs:
- ~[ ] consider not subclassing `numpy.ndarray` (related to #759 )~
- [x] remove some redundancies (esp. w.r.t. to indexing)
- [x] document/simplify indexing behavior
- [x] fix KeyError when wrong lineage is passed - e.g.
  ``KeyError: "Invalid lineage name: `Notoch`. Valid names are: `['Early Blastomeres_1', 'Early Blastomeres_2', 'Notochord']`."`` when passing ``Notochord2`` and ``Notochord`` is present

### PR DESCRIPTION
**Pull request by michalk8**
**IMPORTANT: Please search among the [Pull requests](../pulls) before creating one.**

## Description

Fix :class:`cellrank.tl.Lineage` subsetting (non-existent overlapping keys) and refactor the implementation.

## How has this been tested?

1 new test.

## Closes

closes #777

### CODE REVIEW

**Comment by michalk8** [comment]
@WeilerP could you please check if the bug when merging the lineage names still happens (and/or add a small snippet for me to debug)?

**Comment by WeilerP** [comment]
> @WeilerP could you please check if the bug when merging the lineage names still happens (and/or add a small snippet for me to debug)?

This concerns the incorrect merging of macro states used for absorption probabilities, right? Yes, this fixes it.
Couldn't construct a failure example on the pancreas dataset, though. I tried renaming the cluster `"Beta"` to `"Not Alpha"` but this didn't cause any problems on `cellrank@master`.

**Comment by WeilerP** [comment]
I encountered another weird behavior, though (not sure if it is relevant for this PR):

```python
import numpy as np
import cellrank as cr
import scanpy as sc
import scvelo as scv
from cellrank.tl.kernels import ConnectivityKernel, VelocityKernel
from cellrank.tl.estimators import GPCCA

scv.settings.verbosity = 3
scv.settings.set_figure_params("scvelo")
cr.settings.verbosity = 2

adata = cr.datasets.pancreas_preprocessed()
adata.obs['clusters'].replace({'Alpha': 'EN', 'Beta': 'Posterior EN'}, inplace=True)
scv.utils.show_proportions(adata)

vk = VelocityKernel(adata)
vk.compute_transition_matrix()

ck = ConnectivityKernel(adata).compute_transition_matrix()
combined_kernel = 0.8 * vk + 0.2 * ck

g = GPCCA(combined_kernel)
g.compute_schur(n_components=20)
g.plot_spectrum(real_only=True)

g.compute_macrostates(n_states=3, cluster_key="clusters")
g.plot_macrostates()
```

Throws the error

```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [1], in <module>
     23 g.compute_schur(n_components=20)
     24 g.plot_spectrum(real_only=True)
---> 26 g.compute_macrostates(n_states=3, cluster_key="clusters")
     27 g.plot_macrostates()

File ~/code/cellrank/cellrank/tl/estimators/terminal_states/_gpcca.py:206, in GPCCA.compute_macrostates(self, n_states, n_cells, cluster_key, **kwargs)
    200     logg.warning(
    201         f"Unable to compute macrostates with `n_states={n_states}` because it will "
    202         f"split complex conjugate eigenvalues. Using `n_states={n_states + 1}`"
    203     )
    204     self._gpcca = self._gpcca.optimize(m=n_states + 1)
--> 206 self._set_macrostates(
    207     memberships=self._gpcca.memberships,
    208     n_cells=n_cells,
    209     cluster_key=cluster_key,
    210     params=self._create_params(),
    211     time=start,
    212 )

File ~/code/cellrank/cellrank/tl/estimators/terminal_states/_gpcca.py:988, in GPCCA._set_macrostates(self, memberships, n_cells, cluster_key, check_row_sums, time, params)
    985 self._write_terminal_states(None, None, None, None, log=False)
    987 # fmt: off
--> 988 assignment, colors = self._set_categorical_labels(assignment, cluster_key=cluster_key)
    989 memberships = Lineage(memberships, names=list(assignment.cat.categories), colors=colors)
    990 # fmt: on

File ~/code/cellrank/cellrank/tl/estimators/terminal_states/_term_states_estimator.py:213, in TermStatesEstimator._set_categorical_labels(self, categories, cluster_key, existing)
    211     raise KeyError(f"Unable to find clusters in `adata.obs[{cluster_key!r}]`.")
    212 series_query, series_reference = categories, self.adata.obs[cluster_key]
--> 213 series_reference = series_reference.cat.rename_categories(
    214     {c: str(c) for c in series_reference.cat.categories}
    215 )
    217 # load the reference colors if they exist
    218 if Key.uns.colors(cluster_key) in self.adata.uns:

File ~/miniconda3/envs/cellrank/lib/python3.8/site-packages/pandas/core/generic.py:5487, in NDFrame.__getattr__(self, name)
   5480 if (
   5481     name not in self._internal_names_set
   5482     and name not in self._metadata
   5483     and name not in self._accessors
   5484     and self._info_axis._can_hold_identifiers_and_holds_name(name)
   5485 ):
   5486     return self[name]
-> 5487 return object.__getattribute__(self, name)

File ~/miniconda3/envs/cellrank/lib/python3.8/site-packages/pandas/core/accessor.py:181, in CachedAccessor.__get__(self, obj, cls)
    178 if obj is None:
    179     # we're accessing the attribute of the class, i.e., Dataset.geo
    180     return self._accessor
--> 181 accessor_obj = self._accessor(obj)
    182 # Replace the property with the accessor object. Inspired by:
    183 # https://www.pydanny.com/cached-property.html
    184 # We need to use object.__setattr__ because we overwrite __setattr__ on
    185 # NDFrame
    186 object.__setattr__(obj, self._name, accessor_obj)

File ~/miniconda3/envs/cellrank/lib/python3.8/site-packages/pandas/core/arrays/categorical.py:2601, in CategoricalAccessor.__init__(self, data)
   2600 def __init__(self, data):
-> 2601     self._validate(data)
   2602     self._parent = data.values
   2603     self._index = data.index

File ~/miniconda3/envs/cellrank/lib/python3.8/site-packages/pandas/core/arrays/categorical.py:2610, in CategoricalAccessor._validate(data)
   2607 @staticmethod
   2608 def _validate(data):
   2609     if not is_categorical_dtype(data.dtype):
-> 2610         raise AttributeError("Can only use .cat accessor with a 'category' dtype")

AttributeError: Can only use .cat accessor with a 'category' dtype
```

This is solved when plotting the clusters at some point prior to `g.plot_macrostates()` (which makes the column categorical). The problem does **not** occur, however, if you use

```python
adata.obs['clusters'].replace({'Beta': 'Not Alpha'}, inplace=True)
```

I'm running this with `pandas==1.3.5`. Might be good if we'd convert the column specified in `compute_macrostates` to categorical?

**Comment by michalk8** [comment]
The above error is not relevant, but I also cannot reproduce it (pandas==1.4.2).

**Comment by WeilerP** [comment]
> The above error is not relevant, but I also cannot reproduce it (pandas==1.4.2).

Okay, still want me to open an issue? This is still happening for me after upgrading to `pandas==1.4.2`. I'm using

> cellrank==1.5.1+g97777d93 scanpy==1.8.2 anndata==0.8.0 numpy==1.21.5 numba==0.55.0 scipy==1.7.3 pandas==1.4.2 pygpcca==1.0.3 scikit-learn==1.0.2 statsmodels==0.13.1 python-igraph==0.9.9 scvelo==0.2.4 pygam==0.8.0 matplotlib==3.5.1 seaborn==0.11.2

**Comment by michalk8** [comment]
> Okay, still want me to open an issue? This is still happening for me after upgrading to pandas==1.4.2. I'm using

If the `adata.obs['clusters']` is still categorical after `adata.obs['clusters'].replace({'Beta': 'Not Alpha'}, inplace=True)` (I'd usually call `adata.obs['clusters'].cat.rename_categories({'Beta': 'Not Alpha'}, inplace=True)`), then yes.
Based on the line in the stack trace, I think the `series_reference` is causing problems (adata.obs['clusters']), not the reference, though not 100% certain no modification happens before in our code.

**Pull request merged**
