### PR TITLE
Expose conn_key in ConnectivityKernel

### LINKED ISSUE #493: Introduce spatial proximity kernel
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [x] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

This is a medium-term goal that @giovp and myself discussed. This issue is to serve as a reminder - we'll probably kick of the discussion in ~2 weeks or so. This would fit nicely into our anticipated CellRank 1.3 release, which is going to be all about "CellRank beyond RNA velocity", introducing new kernels and adding tutorials that show how to use CellRank without RNA velocity.

### PR DESCRIPTION
**Pull request by michalk8**
**IMPORTANT: Please search among the [Pull request](../pulls) before creating one.**

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] New feature (non-breaking change which adds functionality)

## Description

Expose `conn_key` in `ConnectivityKernel`'s constructor

## How has this been tested?

3 new tests (1 for low-level, 2 for high-level).

## Closes

closes #493 

TODOs:
- [ ] update docstrings in `cellrank/tl/{_init_term_states.py,
                                                          _transition_matrix.py,
                                                          kernels/_connectivity_kernel.py}`

@Marius1311 could you please handle the docstrings? Would need to just rephrase a bit (mention spatial data, etc.).

### CODE REVIEW

**Comment by Marius1311** [comment]
Hi @michalk8, okay, will do today! Can we assume that the spatial connectivity graph is also always symmetric?

**Comment by Marius1311** [comment]
Okay, I started working on this, there's a bit more work required, this might take me until next week.

**Comment by Marius1311** [comment]
This should be done! I removed the explicit mention of `weight_connectivities` from the docstring in `_initi_term_states` to avoid duplications. Let me know what you think.

**Comment by Marius1311** [comment]
@giovp, would you mind testing this on a spatial graph generated with squidpy?

**Comment by giovp** [comment]
hey, yes on my list, however, I could just test it on random data, but I guess it would be cool to have an actually bio relevant example. For that, I haven't yet found one.

**Comment by Marius1311** [comment]
Great! I think for now it would be good to just test on any spatial graph whether this works, whether warnings come up etc. In particular, I wasn't sure whether the spatial graph is always symmetrized?

**Comment by michalk8** [comment]
Here's the output for the below code
```python
import squidpy as sq
import cellrank as cr

adata = sq.datasets.visium_fluo_adata()
sq.gr.spatial_neighbors(adata)
cr.tl.transition_matrix(adata, conn_key='spatial_connectivities', weight_connectivities=1)
cr.tl.terminal_states(adata, cluster_key='leiden', n_states=9)
cr.tl.lineages(adata)
cr.pl.lineages(adata, basis='spatial', legend_loc=None)
```
index

**Comment by giovp** [comment]
sorry a bit delayed on this but have low capacity until end next week.

> In particular, I wasn't sure whether the spatial graph is always symmetrized?

actually it is not, is that a problem (didn't have time to dig into the implementation sorry). ?

**Comment by Marius1311** [comment]
Hi @michalk8, that looks good, seems to work! Thanks for implementing this. 

@giovp, it's on master now, so feel free to dig into this a bit once you find the time!

**Pull request merged**
