### PR TITLE
Rename final

### PR DESCRIPTION
**Pull request by michalk8**
**IMPORTANT: Please search among the [Pull request](../pulls) before creating one.**

## Title

See below

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)

## Description

Renamed `final` -> `terminal`. Added a new function to set the initial states in the GPCCA estimator.

## How has this been tested?

Yes, 1 test for the newly added function.

## Closes

cloese #372

### CODE REVIEW

**Comment by michalk8** [comment]
@Marius1311 could you please check if everything is fine (i.e. no mention of the `final`, etc?).
The `final` functions are still there and working, but are considered deprecated and will be removed in the next release (the one containing the new GAMs).
Afterwards, we need only to speed up jax and then we will have officially 1.0.0 version (no RC).

TODOs:
- update tutorial notebooks.

**Comment by Marius1311** [comment]
Hi Mike, does this also rename `root` to `initial`? The new set of terms we want to use is `initial/terminal` states.

**Comment by michalk8** [comment]
The `root` should've been dealt with long time ago.

**Comment by michalk8** [comment]
@Marius1311 I've just included your comments regarding the plotting gallery. I am going to merge this later this evening (Monday's coming and I'd like to make a new release).

**Comment by michalk8** [comment]
I've kept the cluster lineages as is, just to let you know.

**Comment by Marius1311** [comment]
Thanks for merging this Mike! Let's talk about the cluster lineage in our next meeting, I do think it needs some work.

**Pull request merged**
