### PR TITLE
Rename min_self_prob to threshold

### LINKED ISSUE #413: Threshold method for `GPCCA.compute_terminal_states`
- [x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

...

### PR DESCRIPTION
**Pull request by michalk8**
**IMPORTANT: Please search among the [Pull request](../pulls) before creating one.**

## Title

@Marius1311 we already did have something like this, it was `method='min_self_prob'`, but I've renamed it to `method='threshold'.`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)

## Closes

closes #413

### CODE REVIEW

**Comment by Marius1311** [comment]
Great, thanks, will look through this just now.

**Comment by Marius1311** [comment]
This works very reliably and we should even consider making this the default method in the next release. 

Would you mind quickly writing a test for this?

**Comment by michalk8** [comment]
Done, merging.

**Comment by Marius1311** [comment]
thx!

**Pull request merged**
