### PR TITLE
Add plot gene corr

### LINKED ISSUE #637: Add estimator-level plotting function for driver genes
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Show genes in scatter plot, correlations with `lin_1` vs. `lin_2`. Optionally, annotate some genes to check with ground truth. Example plot in Fig. 1 below. Code for the function below as well. The function has been called as
```python
# define some gene sets
trophoblast_genes = ['Gata3', 'Elf5', 'Ascl2', 'Phlda2', 'Rhox6', 
                      'Batf3', 'Elf3']
neural_genes = ['Pou3f2', 'Nr2f1', 'Myt1l', 'Scrt2', 'Nhlh2', 'Pou2f2']
stromal_genes = ['Id3', 'Nfix', 'Nfic', 'Prrx1']
genes_oi = {'Neural_1': neural_genes,
            'Trophoblast': trophoblast_genes,
            'Stromal': stromal_genes}

# compute mean gene expression across cells, so we have somethign nice to color the dots by
adata.var['means'] = np.mean(adata.X.A, 0)

# make sure we color gene sets in the lineage colors used above
colors = adata.obsm['to_terminal_states'][list(genes_oi.keys())].colors

# call the actual plotting utility
plot_driver_genes(adata, 
                  lineage_1="Trophoblast", 
                  lineage_2="Neural_1", 
                  genes_oi=genes_oi, 
                  gene_set_colors=colors,
                  color="means", 
                  color_map='RdYlBu_r', 
                  alpha=0.5,
                  title="Putative lineage drivers",
                  size=80)
```

## Fig. 1
image

## Code
```python
def plot_driver_genes(adata: AnnData,
                      lineage_1: str,
                      lineage_2: str,
                      genes_oi: Optional[Dict[str, Iterable]] = None, 
                      gene_set_colors: Optional[Iterable] = None, 
                      figsize: Tuple[int] = (6, 6), 
                      **kwargs):
    """Show scatter plot of gene-correlations with two lineages
    
    Optionally, you can pass a dict of gene names that will be annotated in the plot. 
    
    Note: this based on an idea by Maren Buettner, credit goes to her! See her notebook on gastrulation analysis 
    for the original plot: https://github.com/theislab/gastrulation_analysis/blob/main/6_cellrank.ipynb
    
    Parameters
    --------
    adata
        Annotated data matrix
    lineage_1, lineage_2
        Keys from adata.var
    genes_oi
        Dict of the form `{'gene_set_name': ['gene_1', 'gene_2'], ...}
    gene_set_colors
        List of colors where each entry corresponds to a key from `genes_oi`
    figsize
        Figure size
        
    Returns
    -------
    Nothing, just plots.
    """

    # if gene set to annotate given, create colors (if not passed)
    if genes_oi != None:
        if gene_set_colors is None:

            # import utility and create a set of categorical colors
            from cellrank.tl._colors import _create_categorical_colors
            gene_set_colors = _create_categorical_colors(len(genes_oi.keys()))
    
    # set the figure size
    rcParams['figure.figsize'] = figsize

    # produce the actual scatter plot
    ax = sc.pl.scatter(adata, x = f"to {lineage_1} corr", y = f"to {lineage_2} corr", show=False, 
                      **kwargs)

    # add some lines to highlight the origin
    xmin, xmax = np.min(adata.var[f"to {lineage_1} corr"]), np.max(adata.var[f"to {lineage_1} corr"])
    ymin, ymax = np.min(adata.var[f"to {lineage_2} corr"]), np.max(adata.var[f"to {lineage_2} corr"]) 
    ax.hlines(0, xmin = xmin, xmax=xmax, color='grey', alpha=0.5)
    ax.vlines(0, ymin = ymin, ymax=ymax, color='grey', alpha=0.5)

    # annotate the passed set of genes
    if genes_oi != None:
        for (key, value), color in zip(genes_oi.items(), gene_set_colors):

            # Label names and positions
            mask = np.in1d(adata.var_names, value)
            x = [i for i in adata.var.loc[mask, f"to {lineage_1} corr"]]
            y = [i for i in adata.var.loc[mask, f"to {lineage_2} corr"]]

            # prettify the font
            path_effect = [patheffects.withStroke(linewidth=4, foreground='w',)]

            for i, txt in enumerate(value):
                ax.annotate(txt, xy=(x[i], y[i]), path_effects=path_effect, size=14, c=color) 

    plt.show()
```

### PR DESCRIPTION
**Pull request by michalk8**
**IMPORTANT: Please search among the [Pull request](../pulls) before creating one.**

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] New feature (non-breaking change which adds functionality)

## How has this been tested?

TODO.

## Closes

closes #637

### CODE REVIEW

**Comment by michalk8** [comment]
@Marius1311 ready for review (tests need to still be written). The function is called `plot_lineage_drivers_correlation`.
I've also added an optional param to automatically adjust text, for this, you need to install `adjustText` as `pip install adjustText` + optional legend for the gene sets.

**Comment by Marius1311** [comment]
Very nice, will take a look, thanks.

**Comment by Marius1311** [comment]
Hi Mike, I'll have to look into this one tomorrow!

**Comment by Marius1311** [comment]
I did find the time to look into this now. Comments: 
- when I misspell a lineage, say I write `lineage_y='ophoblast'` instead of `lineage_y='Tophoblast'`, I get `RuntimeError: Compute `.lineage_drivers` first as `.compute_lineage_drivers(..., use_raw=False)`.` Would be more informative to tell me that the lineage hasn't been found, and what the options are. 
- the default plot size is unusually large, the font is very large also, see Fig. 1 below. Let's make it a bit smaller
- also, see Fig. 1 below, I don't think the arrows help much (I don't have `adjust_test` installed yet, will do so in a sec), in fact, they seem to just add confusion. Consider removing them?
- How can I get the legend to display outside of the plot? Remind me of the key I need to pass to `legend_loc` for that to happen? At the moment, the legend is badly in the way, see Fig. 2 below.
- can you issue a warning if `adjust_text=True`, but the package isn't installed, prompting the user to pip-install it?

Sorry, just realized that I had `adjustText` installed all the time. Turning it off gives the plot from Fig. 3 below. So, `adjustText` doesn't work well for me, maybe we can disable it by default?

## Fig. 1
image

## Fig. 2
image

## Fig. 3
image

**Review by Marius1311 — APPROVED** [review]
See minor posted comments. This can be merged once they have been addressed. Well done!

**Comment by michalk8** [comment]
> when I misspell a lineage, say I write lineage_y='ophoblast' instead of lineage_y='Tophoblast', I get RuntimeError: Compute .lineage_driversfirst as.compute_lineage_drivers(..., use_raw=False). Would be more informative to tell me that the lineage hasn't been found, and what the options are.

Done.

> the default plot size is unusually large, the font is very large also, see Fig. 1 below. Let's make it a bit smaller

Done (it was the `dpi`).

> also, see Fig. 1 below, I don't think the arrows help much (I don't have adjust_test installed yet, will do so in a sec), in fact, they seem to just add confusion. Consider removing them?

Agree that `adjustText` isn't perfect, but without arrows, you won't be able to associate the dots with the text, so we should keep it.
I will play around with the params, but `adjust_text` is `False` by default now.

> How can I get the legend to display outside of the plot? Remind me of the key I need to pass to legend_loc for that to happen? At the moment, the legend is badly in the way, see Fig. 2 below.

It's `'upper right out'`.

> can you issue a warning if adjust_text=True, but the package isn't installed, prompting the user to pip-install it?

It was already there, changed logging level to `ERROR`.

**Comment by michalk8** [comment]
Didn't find any better params, kept the defaults.

**Pull request merged**
