### PR TITLE
Extra krylov

### LINKED ISSUE #246: Add extra install for krylov method
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [x] Other?

Instead of listing out all 4 extra things to be installed in https://cellrank.readthedocs.io/en/latest/installation.html,
add an option like `pip install cellrank[krylov]` that will install them (libopenmpi is still a necessary precursor).
Also see if it's possible to do it through conda as well.

### PR DESCRIPTION
**Pull request by michalk8**
**IMPORTANT: Please search among the [Pull request](../pulls) before creating one.**

## Title
Installation improvement of SLEPc and PETSc

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] New feature (non-breaking change which adds functionality)

## Description
Add option for `pip install cellrank[krylov]` as a convenience method to install SLEPc and PETSc.

## How has this been tested?
I've added a CI to see if it works.

## Closes
closes #246

### CODE REVIEW

**Comment by Marius1311** [comment]
Very nice PR template :)
If you want, we can try this on my machine during our call.

**Comment by michalk8** [comment]
@Marius1311 could you please check this out? I.e. create an empty conda environment and try `pip install -e.[krylov]`.
The build on Travis seems to pass, which is great! You might want to remove your pip cache, should be under `$HOME/.cache/pip`, at least on linux.

**Comment by michalk8** [comment]
Todos before new release:
- [ ] renaming https://github.com/theislab/cellrank/issues/254 (+ possibly 1 other) (MK)
- [ ] merge https://github.com/theislab/cellrank/issues/219 (ML)
- [ ] automate bioconda upload (MK) - I remember seeing it somewhere, can't find it anymore, maybe in bioconda-utils

**Comment by Marius1311** [comment]
Sure, can give this a go. Can I also just run `pip install[krylov]`?

**Comment by michalk8** [comment]
I'm merging this because I want to test bioconda with krylov. We wil add the changes above in a later release.

**Comment by Marius1311** [comment]
awesome, thanks. Let's also talk about this later over the phone.

**Pull request merged**
