### PR TITLE
Minor update to cell type composition plotting

### PR DESCRIPTION
**Pull request by Marius1311**
**IMPORTANT: Please search among the [Pull request](../pulls) before creating one.**

## Title
Passes keyworded arguments to the cell type plotting functions

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)

## Description
Passes keyworded arguments to the cell type plotting functions

## How has this been tested?
I still have to add tests.

### CODE REVIEW

**Comment by Marius1311** [comment]
Hi @michalk8 , I added a test for this but I'm not quite sure how to add the ground truth figures, can you explain this to me please?

**Comment by michalk8** [comment]
Hi @Marius1311 , it's really simple - after running the plotting function as `pytest -k "the function name"`, it's saved under figures (same is same as the function name),

**Comment by michalk8** [comment]
For future reference, the command to move it was `mv tests/figures/composition_kwargs_autopct.png tests/_ground_truth_figures/`.

**Comment by Marius1311** [comment]
thanks Mike!

**Comment by michalk8** [comment]
@Marius1311 do you have pre-commit enabled? I.e. did you run after the reclone of the repo `pre-commit install` in repo's root directory? Asking because I had to blacken the files.

**Comment by Marius1311** [comment]
> @Marius1311 do you have pre-commit enabled? I.e. did you run after the reclone of the repo `pre-commit install` in repo's root directory? Asking because I had to blacken the files.

yes, that's enabled, not sure what happened there.

**Pull request merged**
