### PR TITLE
Add the preprint link

### PR DESCRIPTION
**Pull request by Marius1311**
**IMPORTANT: Please search among the [Pull request](../pulls) before creating one.**

## Title
Add info to the README files

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)

## Description
This adds the link to our preprint and a short explanation of the name `CellRank`

## How has this been tested?
No testing necessary, only docs.

### CODE REVIEW

**Comment by Marius1311** [comment]
@michalk8 , would be nice to add a category under `Types of changes` to the PR template for changes to the docs.

**Comment by Marius1311** [comment]
Hi @michalk8 , please take a quick look at this.

**Review by michalk8 — APPROVED** [review]

**Comment by michalk8** [comment]
@Marius1311 shall we merge this?

**Comment by michalk8** [comment]
I will change the PR template later. Btw, you can disable travis when you prefix your comit mesages as e.g. `[ci skip]` - in this case it's mostly useless (pre-commit checks if the RST files are bad or not).

**Comment by Marius1311** [comment]
One thing: we should use the doi for the preprint link, please update.

**Comment by michalk8** [comment]
Done - you can merge this I think (from my side).

**Comment by Marius1311** [comment]
Nice, feel free to merge.

**Pull request merged**
