### PR TITLE
Fix cl fates

### LINKED ISSUE #87: Handeling both legends in PAGA pie
Getting both legends to somehow not overlap with the data is a real challenge. What's missing is the option to position the cellrank legend (`final_states`) outside of the data, like the scvelo/scanpy legend (`clusters`). 

image
scvelo legend is set to `right`, cellrank legend is `left`. The problem is, it's not really outside the plotting area. `best` does not give me anything better:
image

If at least I could turn the `clusters` legend off, and if I were able to put the cellrank legend to the place there the scvelo legend currently is, that would already help me a lot.

### PR DESCRIPTION
**Pull request by michalk8**
Fixes #87 and hopefully #86

### CODE REVIEW

**Comment by michalk8** [comment]
@Marius1311 I implemented the outside legend, you can do stuff like `'top left out'` to specify it.
Should be working for both abs. prob. legend and cluster legend in `'paga_pie'`.

**Comment by michalk8** [comment]
As for #86 , let me know it it still doesn't work and I wil scour the internet for more info about this.
You're testing it on Mac, right?

**Comment by Marius1311** [comment]
thanks a lot Mike! I will get back to you later about this.

**Comment by Marius1311** [comment]
Legend positioning works very well now, thanks.

**Comment by Marius1311** [comment]
saving as pdf still displays cluster legend on data for me, on Mac. As long as I could alternatively save in png, that would be fine but there is a problem as well: saving in png ignores the passed dpi. Please try to reproduce: save the figure as png (or anything else, just not pdf), one with really high and once with really low dpi and check whether there is any difference. 

The problem for me is: there is no way to save a paga with pie charts with correct legend positioning in high resolution.

**Comment by michalk8** [comment]
Could you please post here the specific command you're trying to run + which data you're using?
I will try to replicate this, but this seems more like matplotlib issue.

**Comment by Marius1311** [comment]
Sure, I'm calling like this: 

````python
# set paga and cellrank parameters
paga_kwargs={'fontsize': 15,  'node_size_scale': 2, 'frameon': False, 
              'threshold': 0.1, 'max_edge_width': 4, 'edge_width_scale': 1.5, 
             'legend_loc': 'right'}
cellrank_kwargs = {'title': f'fate probabilities at E{t_point}', 'legend_kwargs': {'loc': None}}

# plot, maybe save
if save_figure: cellrank_kwargs['save'] = f'{t_point}_paga_pie.png'
cr.pl.cluster_fates(adata_t, cluster_key='clusters', mode='paga_pie', basis="umap", 
                    **cellrank_kwargs, **paga_kwargs)
````

I will upload the data to seafile and send you a link in slack.

**Pull request merged**
