### PR TITLE
Update release notes

### LINKED ISSUE #646: Release notes 1.4
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

...

### PR DESCRIPTION
**Pull request by michalk8**
**IMPORTANT: Please search among the [Pull request](../pulls) before creating one.**

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)

## Description

@Marius1311 there are 2 TODOs (link to bibtex PR and WOT tutorial PR) that you should fill. Also, please try to improve
the wording/order and check for any obvious typos.

## How has this been tested?

NA
## Closes

closes #646

### CODE REVIEW

**Comment by Marius1311** [comment]
Thanks for preparing this, I will take care of this.

**Comment by michalk8** [comment]
> Thanks for preparing this, I will take care of this.

No worries, I'm just fixing installation again, hopefully should be fine. Otherwise, will have to disable 3.9 testing (it's the pinned version of `umap-learn` from scVelo that causes the issue).

**Comment by michalk8** [comment]
@Marius1311 please also add `real_time` to `docs/source/index.rst`.

**Review by Marius1311 — APPROVED** [review]
Done - release notes look very nice. We honestly did a lot of stuff here!

**Pull request merged**
