### PR TITLE
Feature/refactor kernels

### LINKED ISSUE #772: Refactor kernels
TODOs:
- [x] differentiate between directional and non-directional
- [x] make inversion not an inplace operation
- [x] don't compute `CytoTRACE` score on initialization
- [x] remove adaptive scaling (if reintroduced, will be added in a better form)
- [x] use elementwise multiplication when multiplying 2 kernels, not matmul
- [x] move `_tmap_as_tmat` from #664 
- [x] refactor `RandomWalk` class to include plotting
- [x] refactor `compute_projection`
- [x] add a better way of handling optional connectivities (`ConnectivityMixin`?)
- [x] add common decorator to check whether `.transition_matrix` is present
- [x] remove condition number check?
- [x] add docs/comments for some internal code
- [x] improve public docstrings

### PR DESCRIPTION
**Pull request by michalk8**
**IMPORTANT: Please search among the [Pull requests](../pulls) before creating one.**

## Description

Refactor kernel module. These changes include:
- allow kernel elementwise multiplication
- decouple CytoTRACE computation from kernel initialization, see :meth:`cellrank.tl.kernels.CytoTRACEKernel.compute_cytottrace`
- change argument ``mode`` to ``model`` in :class:`cellrank.tl.kernels.VelocityKernel`
- change argument ``scheme`` to ``similarity`` in :class:`cellrank.tl.kernels.VelocityKernel`
- remove ``'sampling'`` option in :class:`cellrank.tl.kernels.VelocityKernel`
- distinguish between unidirectional and bidirectional kernels
- bidirectional kernel inversion is no longer inplace, returns a new object
- add more memory efficient way of copying kernels
- improve :class:`cellrank.kernels.PrecomputedKernel`
- abstract kernel-related plotting functions (projection and random walks)
- temporarily remove kernel tricks examples
- fix various typos in docstrings
- fix corner-case bug when computing absorption probabilities
- fix not setting transport maps in :class:`cellrank.tl.kernels.TransportMapKernel`
- fix automatic threshold removing 1 row in :class:`cellrank.tl.kernels.TransportMapKernel` 

## How has this been tested?

Added a few new tests.

## Closes

closes #772

### CODE REVIEW

**Comment by Marius1311** [comment]
Thanks @michalk8 for this wonderful piece of work, I'm just going to note down some comments as I go along
- Let `vk` be a velocity kernel. Why does `vk.plot_single_flow()` exist? Shouldn't this only exist for time-series kernels? Or if necessary, also pseudotime kernels? 
- Let `ck` be a connectivity kernel. First running `vk.plot_projection()` produces the expected result, however, thereafter running `ck.plot_projection()` produces the same plot, which is wrong. 
- `ck.plot_random_walks()` does not have this issue
-  Same question about `plot_single_flow` for the ConnectivityKernel. Seems like an unnecessary function to have here. Rather hide this from the user? 
- Let `pk` be a pseudotime kernel. Same issue with `pk.plot_projection()` as above. Note that I'm running all of these in the same notebook. 
- Again, `pk.plot_random_walks` does not suffer from this problem
- Let `g` be a GPCCA estimator object. Suggestion: should we add an option to sort the order in which the macrostates appear in `g.plot_coarse_T()`? So far, it's just random. However, sorting by e.g. the amount of outgoing probability mass (from high to low) or the self-transition probability makes a lot of sense from a practical point of view. I would vote to have this as an option, with the default being `by_outgoing`. That would place initial states early and terminal states late. 
- I'm always a bit disappointed when running `g.compute_terminal_states()` because it produces no output (there's no bug here) - maybe let's print the identified terminal states? Of course, the same holds for `g.predict()`. 

Other than that, everything worked fine.

**Comment by Marius1311** [comment]
@dawe, I know you're quite an active CellRank user - would you mind running this PR on some of your analysis to tell us whether everything works as expected? @michalk8 did quite an extensive refactoring. I myself looked at the `VelocityKernel`, `ConnectivityKernel` and `PseudoTimeKernel` as well as the `GPCCA` estimator so far.

**Comment by Marius1311** [comment]
@WeilerP and @ManuelGander, both of you use the `RealTime` kernel quite a bit - would you mind testing whether everything still works as expected after @michalk8's refactoring? @ManuelGander, you will have to check out this branch locally to test the changes, please let me know if you have difficulties doing this, I'm happy to help.

**Comment by Marius1311** [comment]
@michalk8, would you be able to tell us whether there are parts of the code that deserve particular attention?

**Comment by Marius1311** [comment]
Thanks @michalk8. 
- Re `plot_single_flow`: ok, let's leave it
- Re embedding projections: let's log it, i.e. let's use `info` level

@WeilerP, do you think you could have a quick look at the three areas @michalk8 highlighted above, i.e. just run in your own examples and see whether it works? Would be great to finally merge this PR.

**Comment by Marius1311** [comment]
Todo's here:
- @WeilerP will check this out
- @michalk8 will write tests and implement simple ordering scheme for macrostates in `P_coarse`

**Comment by Marius1311** [comment]
Hi @michalk8, would you like me to check this out again, or what's the current status of this?

**Comment by michalk8** [comment]
As before, 3.8 PETSc fails because of installation, will be fixed in #803 .

**Comment by Marius1311** [comment]
Amazing @michalk8, thanks so much for this massive push! Really great to see the kernel interface getting even better.

**Pull request merged**
