### PR TITLE
Speed up calculation of absorption probabilities

### LINKED ISSUE #619: Speed up the computation of absorption probabilities
- [x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Currently, when we want to compute absorption probabilities towards terminal macrostates, we select the N most confidently assigned cells per macrostate (by default, N=30) and we compute absorption probabilities towards them individually. Afterwards, we sum up absorption probabilities across all cells assigned to the same macrostates, to get one number per macrosate. However, this can be massively speed up by creating one pseudo-cell per macrostate which summarizes these N cells and computing absorption probabilities towards just these. Ignoring parallelisation, that's a speed up by factor N, i.e. 30 by default. 

to do's include
- make sure there are regression tests for absorption probabilities before changing anything. If we don't have any, add at least one. 
- implement the new routine based on the pseudo-cells
- make sure tests (esp. regression tests) pass

### PR DESCRIPTION
**Pull request by WeilerP**
**IMPORTANT: Please search among the [Pull request](../pulls) before creating one.**

# Speed up calculation of absorption probabilities

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)

## Description

Changes the computation of absorption probabilities according to @Marius1311 suggestion in #619.

## How has this been tested?

Unit tests already exist. `tests/test_cflare.py::TestCFLARE.test_abs_probs_negative` needs to be updated.

## Closes

Closes #619.

### CODE REVIEW

**Comment by WeilerP** [comment]
@michalk8, `tests/test_cflare.py::TestCFLARE.test_abs_probs_negative` [here](https://github.com/theislab/cellrank/blob/f90ae2b2e87acf5d4f39492a803d060f8a688524/tests/test_cflare.py#L617) fails now since `cellrank.tl.estimators._base_estimator._solve_lin_system` now already returns the summed probabilities. Consequently, two values are now negative. I suggest to simply update the matching string accordingly. Or do you prefer a different solution?

**Comment by michalk8** [comment]
> I suggest to simply update the matching string accordingly. 

Agree, thanks!

**Comment by Marius1311** [comment]
Fantastic, thanks. Can we compare this in a unit test to previous, summed absorption probabilities? i.e. does the test you mention above do that on a test case problem @WeilerP?

**Comment by WeilerP** [comment]
> Fantastic, thanks. Can we compare this in a unit test to previous, summed absorption probabilities? i.e. does the test you mention above do that on a test case problem @WeilerP?

Unit tests checking the correct calculation of absorption probabilities already exist (e.g. [here](https://github.com/theislab/cellrank/blob/f4a08e62f9edb4d3e97f82c6129ad083d43cfd04/tests/test_gpcca.py#L443)) and are still passing, i.e. the old and new implementations give the same result. The test I mentioned is only designed to trigger `ValueError` which circumvents the actual calculation of absorption probabilities to speed up the unit test.

**Comment by Marius1311** [comment]
We just need some statement on the speedup now - that's why we did this in the first place. I would like to know whether we really get something in the range of 4x speedup on a medium sized dataset (~50k cells)

**Review by michalk8 — APPROVED** [review]

**Comment by michalk8** [comment]
LGTM. Re failing macOS test: not sure what's happening on GA, but it seems slow - just ignore it for now.

**Comment by Marius1311** [comment]
I'll also check this out today on the reprogramming data to see what speedup we get.

**Comment by WeilerP** [comment]
> I'll also check this out today on the reprogramming data to see what speedup we get.

Cool. I decided to test it on the arabidopsis dataset (which is similar in size I guess).

**Comment by Marius1311** [comment]
> > I'll also check this out today on the reprogramming data to see what speedup we get.
> 
> Nice! I decided to test it on the arabidopsis dataset (which is similar in size I guess).

yes! That's a good idea. Esp. for many terminal states, we should see significant speedup. If not, we have to check whether parallelization still does what it should. Original parallelization, @michalk8, was optimized to solve many linear solved, i.e. in the range of 60-150. With the new implementations, we will be looking at 2-10 linear solves, in most problems.

**Comment by Marius1311** [comment]
I tested this on a subsampled version of the reprogramming data (41.5k cells) on my laptop for 4 terminal states by calling
`g.compute_absorption_probabilities(n_jobs=n_jobs, solver='gmres', use_petsc=True)`. I get the following results

- old runtime (8 cores): 8m 42sec
- new runtime (8 cores): 1m 29sec
- new runtime (4 cores): 1m 25sec
- new runtime (1 core): 1m 15sec

So, this is great. I take two things from this:
1. It worked! No matter how many cores I use, I get at least 5x speedup. 
2. For such a low number of linear systems, parallelisation actually does not help and it's faster using a single core. This probably changes when we consider more terminal states.

@WeilerP, from my point of view, this can be merged as soon as tests pass. What sort of speedup did you see in your tests? Similar?

**Comment by Marius1311** [comment]
I should note one thing here: the reason why absorption probabilities take relatively long here is because I used the WOT kernel to compute the transition matrix. Unfortunately, solving an entropically-regularized OT problem leads to dense solutions, hence, the transition matrix has dense blocks on the 1st off-diagonal. Luckily, these are not that large because the number of cells per time point is reasonable. This becomes problematic for datasets with extremely large cell numbers distributed across few time-points - that would mean very large dense matrices which would massively slow down our linear solver. 

So, if I repeated the same experiment using e.g. the `VelocityKernel`, I would expect to see computation times much lower. In the CellRank paper, we compute absorption probs. for 100k cells on the server in 2 min (using the `VelocityKernel`).

**Comment by michalk8** [comment]
Merging this (MacOS is expected to fail right now).

**Comment by WeilerP** [comment]
@Marius1311, sorry for the delayed reply. I ran it on the [mouse gastrulation data](https://www.nature.com/articles/s41586-019-0933-9) containing ~90000 cells and 6 terminal states:

* old implementation (6 cores): 3:35min
* new impelementation (6 cores): 9sec
* new implementation (1 core): 28sec

So the new implementation is whopping 24 times (ish) faster.

> 2. For such a low number of linear systems, parallelisation actually does not help and it's faster using a single core. This probably changes when we consider more terminal states.

Just as a side remark: I would not expect an increase in performance using more than 4 cores since there were only 4 terminal states, i.e. only 4 processes to parallelize.

**Comment by Marius1311** [comment]
Thanks for these results! This is really great, it's a fantastic speedup. Being able to process 90k cells in 9 seconds is just fantastic!

As to the number of cores, you are right, for 4 terminal states, it doesn't make sense to use more than 4 cores. I was doing this to see whether using more cores than terminal states, in which case we should prevent the user from doing this by setting the number of cores equal to the number of terminal states and issuing a warning. I ended up not doing it because the performance loss wasn't great, so I thought it doesn't really matter. Feel free to open a PR to fix this - it's minor but user-friendly.

**Comment by michalk8** [comment]
>Just as a side remark: I would not expect an increase in performance using more than 4 cores since there were only 4 terminal states, i.e. only 4 processes to parallelize.
> As to the number of cores, you are right, for 4 terminal states, it doesn't make sense to use more than 4 cores. 

That's because n the parallelize function, you can't use more cores than jobs, I clip it.

**Comment by Marius1311** [comment]
Nice. Would be good to issue a warning about this.

**Pull request merged**
