### PR TITLE
Add high level function to compute lineage drivers

### PR DESCRIPTION
**Pull request by Marius1311**
So far, this is only possible via the low-level interface. Add possiblitiy to call this from the high level interface.

### CODE REVIEW

**Comment by Marius1311** [comment]
Seems to work, but needs at least very basic tests to make sure works fine for forward/backwards cases.

**Comment by Marius1311** [comment]
@michalk8 , this is a bit clunky because I have a lot of repeated documentation - is there a way to make this more elegent? In essence, I would like to re-use part of the docstring of the low-level method `self.compute_lineage_drivers`.

**Comment by michalk8** [comment]
We could try: https://github.com/Chilipp/docrep

**Comment by Marius1311** [comment]
This looks pretty cool, I just didn't figure our from their documentation whether this would work if the functions are in different python files.

**Comment by Marius1311** [comment]
I will attempt to merge this later today without docrep, but I will open a low-priority issue so we can do this later.

**Comment by Marius1311** [comment]
I added tests for the high level pipelines and check whether all keys are created, should be fine now.

**Pull request merged**
